# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: etzba

cli:
  name: etzba-cli
  image:
    repository: nadavbm/etzba
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  cliSets: 
    - command: [ "./etz", "api", "--config=/data/config.yaml", "--workers=3", "--rps=15", "--duration=30s", "--verbose" ]
      sleep: [ "/bin/sh", "-c", "sleep 30" ]
    - command: [ "./etz", "api", "--config=/data/config.json", "--workers=5", "--rps=25", "--duration=30s", "--verbose" ]
      sleep: [ "/bin/sh", "-c", "sleep 120" ]
    - command: [ "./etz", "api", "--config=/data/config.yaml", "--workers=7", "--rps=35", "--duration=30s", "--verbose" ]
      sleep: [ "/bin/sh", "-c", "sleep 180" ]
    - command: [ "./etz", "api", "--config=/data/config.json", "--workers=9", "--rps=45", "--duration=30s", "--verbose" ]
      sleep: [ "/bin/sh", "-c", "sleep 240" ]
    - command: [ "./etz", "api", "--config=/data/config.yaml", "--workers=12", "--rps=60", "--duration=30s", "--verbose" ]
      sleep: [ "/bin/sh", "-c", "sleep 300" ]
    - command: [ "./etz", "api", "--config=/data/config.json", "--workers=15", "--rps=90", "--duration=30s", "--verbose" ]

api: 
  name: etzba-api
  image:
    repository: nadavbm/etzba-api-test
    pullPolicy: IfNotPresent
    tag: "latest"
  url: etzba-api-svc
  containerPort: 8080
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

pg: 
  name: etzba-pg
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: "14"
  containerPort: 5432
  resources:
    limits:
      cpu: 600m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  credentials:
    username: "etzba"
    password: "etzba123"
    database: "etzba"
