apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cli.name }}
spec:
  #activeDeadlineSeconds: 30
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: {{ .Values.cli.name }}
        image: {{ .Values.cli.image.repository }}:{{ .Values.cli.image.tag }}
        {{- range .Values.cli.cliSets }}
        command: {{ .command }}
        lifecycle:
          postStart:
            exec:
              command: {{ .sleep }}
        {{- end }}
        env:
        - name: ETZ_API_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cli.name }}-sec
              key: method
        - name: ETZ_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cli.name }}-sec
              key: token
        volumeMounts:
          - name: {{ .Values.cli.name }}-cfg
            mountPath: /data/config.yaml
            subPath: config.yaml
          - name: {{ .Values.cli.name }}-cfg
            mountPath: /data/config.json
            subPath: config.json
      volumes:
        - name: {{ .Values.cli.name }}-cfg
          configMap:
            name: {{ .Values.cli.name }}-cfg
      restartPolicy: OnFailure
  backoffLimit: 4
