apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cli.name }}
spec:
  #activeDeadlineSeconds: 30
  completions: 3
  parallelism: 1
  template:
    spec:
      containers:
      - name: {{ .Values.cli.name }}
        image: {{ .Values.cli.image.repository }}:{{ .Values.cli.image.tag }}
        command: [ "./etz", "api", "--config=/data/config.yaml", "--workers=2", "--rps=4", "--duration=180s", "--verbose" ]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 20"]
        env:
        - name: ETZ_API_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cli.name }}-sec
              key: method
        - name: ETZ_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cli.name }}-sec
              key: token
        - name: PROMETHEUS_PUSH_GATEWAY
          value: prometheus.prometheus.svc.cluster.local
        volumeMounts:
          - name: {{ .Values.cli.name }}-cfg
            mountPath: /data/config.yaml
            subPath: config.yaml
      volumes:
        - name: {{ .Values.cli.name }}-cfg
          configMap:
            name: {{ .Values.cli.name }}-cfg
      restartPolicy: OnFailure
  backoffLimit: 4