apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.cli.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.cli.name }}
        image: {{ .Values.cli.image.repository }}:{{ .Values.cli.image.tag }}
        command: [ "./etz", "api", "--workers=3", "--helpers=/data/helpers.yaml", "--verbose" ]
        env:
        - name: ETZ_API_AUTH_METHOD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cli.name }}-sec
              key: method
        - name: ETZ_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cli.name }}-sec
              key: token
        volumeMounts:
          - name: {{ .Values.cli.name }}-cfg
            mountPath: /data/helpers.yaml
            subPath: helpers.yaml
      volumes:
        - name: {{ .Values.cli.name }}-cfg
          configMap:
            name: {{ .Values.cli.name }}-cfg
      restartPolicy: Never
  backoffLimit: 4