apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pg.name }}-sec
data:
  postgres_database: {{ .Values.pg.credentials.database | b64enc }}
  postgres_user: {{ .Values.pg.credentials.username | b64enc }}
  postgres_password: {{ .Values.pg.credentials.password | b64enc }}