version: '3'

services:
  pg-database:
    image: 'postgres:14'
    environment:
      - POSTGRES_USER=etzba
      - POSTGRES_PASSWORD=Pass1234
      - POSTGRES_DB=etzba
    ports:
      - "5432:5432"
    restart: always